### PR TITLE
kep draft for metacontoller as a subproject

### PR DESCRIPTION
**Pull request by alaimo**
Initial draft for the Metacontroller KEP. This is a slightly revised version of this community document. @AmitKumarDas please review and comment. We can iterate as needed. I left metac out of this. I think we should focus on finding a permanent home for metacontroller, then bring some, or all, of the enhancements in metac into the project. Once we finalize this PR, I'll merge to my fork's master branch, then per @AmitKumarDas, I will:

1. Submit a PR to https://github.com/kubernetes/enhancements
1. Open an issue request for repo migration in https://github.com/kubernetes/org/issues/new/choose
1. Drop an email with the PR for step 1 and issue from step 2
1. On a week day post the stuff from above to slack #sig-api-machinery channel
1. Add an agenda item in next sig-api-machinery weekly meeting

@DirectXMan12
@enisoc
@mikebryant
@piersharding
@luisdavim
@rosenhouse
@kmova
@droot

### CODE REVIEW

**Comment by piersharding** [comment]
Hi @alaimo - thanks for doing this, much appreciated.  This seems to capture all the main points and lays out a good plan for moving forward.
Cheers,
Piers.

**Comment by AmitKumarDas** [comment]
thanks @alaimo . KEP looks great.

**Review by AmitKumarDas — APPROVED** [review]
/lgtm

**Review by kmova — APPROVED** [review]
Thanks @alaimo for putting this together. Looks great!

**Comment by alaimo** [comment]
Thanks everyone. I'll leave this until Monday. Unless anyone objects, on Tuesday, I'll merge this down and open the PR against the upstream repository.

**Pull request merged**
